### ISSUE TITLE
Support Angular 4

### ISSUE THREAD

**Issue by chalin** [dart-league/ng_bootstrap#74]
4.0.0-alpha is out

**Comment by chalin** [comment]
When using an app with 4.0.0-alpha+2 and ng_bootstrap I get the following error when attempting to pub get:
```
Loading angular and dart_to_js_script_rewriter transformers...
[BuilderTransformer: Instance of 'LibraryBuilder' on ng_bootstrap|primary]:
Error running TemplateGenerator for ng_bootstrap|lib/components/datepicker/index.dart.
Error: Bad state: Failed to parse @Component annotation for BsDatePickerComponent:
One or more of the following arguments were unresolvable: 
* BsDayPickerComponent
* BsMonthPickerComponent
* BsYearPickerComponent
* CORE_DIRECTIVES
* FORM_DIRECTIVES
The root cause could be a mispelling, or an import statement that 
looks valid but is not resolvable at build time. Bazel users should 
check their BUILD file to ensure all dependencies are listed.


Stack Trace:
#0      NormalizedComponentVisitor._failFastOnUnresolvedTypes (package:angular/src/source_gen/template_compiler/find_components.dart:96:5)
#1      NormalizedComponentVisitor._visitTypeObjects (package:angular/src/source_gen/template_compiler/find_components.dart:132:13)
#2      NormalizedComponentVisitor._visitTypes.<anonymous closure> (package:angular/src/source_gen/template_compiler/find_components.dart:77:33)
#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#4      new List.from (dart:core-patch/array_patch.dart:46)
#5      Iterable.toList (dart:core/iterable.dart:347)
#6      NormalizedComponentVisitor._visitTypes (package:angular/src/source_gen/template_compiler/find_components.dart:87:10)
#7      NormalizedComponentVisitor._visitDirectives (package:angular/src/source_gen/template_compiler/find_components.dart:59:7)
#8      NormalizedComponentVisitor.visitClassElement (package:angular/src/source_gen/template_compiler/find_components.dart:43:24)
#9      AbstractClassElementImpl.accept (package:analyzer/src/dart/element/element.dart:120:15)
#10     ElementImpl.safelyVisitChildren (package:analyzer/src/dart/element/element.dart:3091:15)
#11     CompilationUnitElementImpl.visitChildren (package:analyzer/src/dart/element/element.dart:1757:5)
#12     RecursiveElementVisitor.visitCompilationUnitElement (package:analyzer/dart/element/visitor.dart:207:13)
#13     CompilationUnitElementImpl.accept (package:analyzer/src/dart/element/element.dart:1616:15)
#14     ElementImpl.safelyVisitChildren (package:analyzer/src/dart/element/element.dart:3091:15)
#15     LibraryElementImpl.visitChildren (package:analyzer/src/dart/element/element.dart:6352:5)
#16     RecursiveElementVisitor.visitLibraryElement (package:analyzer/dart/element/visitor.dart:267:13)
#17     LibraryElementImpl.accept (package:analyzer/src/dart/element/element.dart:6221:15)
#18     findComponentsAndDirectives (package:angular/src/source_gen/template_compiler/find_components.dart:27:11)
#19     processTemplates.<anonymous closure> (package:angular/src/source_gen/template_compiler/template_processor.dart:54:13)
#20     logElapsedSync (package:angular/src/source_gen/common/logging.dart:26:27)
#21     processTemplates (package:angular/src/source_gen/template_compiler/template_processor.dart:53:50)
<asynchronous suspension>
#22     TemplateGenerator.generate.<anonymous closure> (package:angular/src/source_gen/template_compiler/generator.dart:29:27)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1120)
#24     _CustomZone.run (dart:async/zone.dart:1001)
#25     runZoned (dart:async/zone.dart:1467)
#26     TemplateGenerator.generate (package:angular/src/source_gen/template_compiler/generator.dart:28:12)
<asynchronous suspension>
#27     _generate (package:source_gen/src/builder.dart:203:35)
<asynchronous suspension>
#28     _Builder._generateForLibrary (package:source_gen/src/builder.dart:79:15)
<asynchronous suspension>
#29     _Builder.build (package:source_gen/src/builder.dart:69:11)
<asynchronous suspension>
#30     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:35:21)
<asynchronous suspension>
#31     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#32     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#33     Future.wait (dart:async/future.dart:355)
#34     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:41:31)
#35     _rootRun (dart:async/zone.dart:1120)
#36     _CustomZone.run (dart:async/zone.dart:1001)
#37     runZoned (dart:async/zone.dart:1467)
#38     scopeLog (package:build/src/builder/logging.dart:12:38)
#39     runBuilder (package:build/src/generate/run_builder.dart:41:9)
<asynchronous suspension>
#40     BuilderTransformer._apply (package:build_barback/src/transformer/transformer.dart:94:11)
<asynchronous suspension>
#41     BuilderTransformer.apply.<anonymous closure> (package:build_barback/src/transformer/transformer.dart:51:46)
#42     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#43     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#44     Future.wait (dart:async/future.dart:355)
#45     BuilderTransformer.apply (package:build_barback/src/transformer/transformer.dart:51:19)
<asynchronous suspension>
#46     _EagerAggregateTransformerWrapper.apply (package:angular/src/transform/common/eager_transformer_wrapper.dart:36:59)
#47     _serializeAggregateTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:$pub/serialize/transformer.dart:72:16)
#48     new Future.sync (dart:async/future.dart:206)
#49     _serializeAggregateTransformer.<anonymous closure>.<anonymous closure> (package:$pub/serialize/transformer.dart:70:20)
#50     respond.<anonymous closure> (package:$pub/serialize.dart:150:33)
#51     new Future.sync (dart:async/future.dart:206)
#52     respond (package:$pub/serialize.dart:150:7)
#53     _serializeAggregateTransformer.<anonymous closure> (package:$pub/serialize/transformer.dart:57:5)
#54     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#58     _StreamController._add (dart:async/stream_controller.dart:667)
#59     _StreamController.add (dart:async/stream_controller.dart:613)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
[BuilderTransformer: Instance of 'LibraryBuilder' on ng_bootstrap|primary]:
Error running TemplateGenerator for ng_bootstrap|lib/components/input/input.dart.
Error: Bad state: Failed to parse @Component annotation for BsInput:
One or more of the following arguments were unresolvable: 
* BsMinLengthValidator
* BsMaxLengthValidator
* CORE_DIRECTIVES
* FORM_DIRECTIVES
The root cause could be a mispelling, or an import statement that 
looks valid but is not resolvable at build time. Bazel users should 
check their BUILD file to ensure all dependencies are listed.
```

cc @kwalrath

**Comment by luisvt** [comment]
Could you show the sample app?

**Comment by rbishop-bah** [comment]
It may not be the only thing but alpha+2 changed `FORM_DIRECTIVES` to `formDirectives`

**Comment by chalin** [comment]
Edit: `examples/ng_test/github_issues` from https://github.com/dart-lang/site-webdev/pull/931

---

~Btw, atm I'm unable to successfully run _any_ of my angular_test-based tests so maybe we should wait before investigating further.~

~Anyhow, you can get the code to reproduce this from https://github.com/dart-lang/site-webdev/pull/910. The example source is under `examples/ng_test/github_issues`, using this updated pubspec:~
```yaml
name: ng_test.github_issues
description: Demo of angular_test
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0-alpha+2
  markdown: ^0.11.3
  ng_bootstrap: ^0.7.0
  sass_transformer: ^0.1.2+1

dev_dependencies:
  angular_test: ^1.0.0-beta+5
  browser: 0.10.0+2
  mockito: ^2.0.2
  pageloader: ^2.2.5
  test: ^0.12.21

transformers:
- angular:
    entry_points: web/main.dart
- angular/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
```

~I haven't yet tried without the `reflection_remover`. I'll do that the next time I give this a try.~

**Comment by chalin** [comment]
> Could you show the sample app?

@luisvt try pub serving `examples/ng_test/github_issues` from https://github.com/dart-lang/site-webdev/pull/931

**Comment by chalin** [comment]
As @rbishop-bah, mentioned, there are still references to `FORM_DIRECTIVES ` though there might be other issues too:
```nocode
# ng_bootstrap-0.7.0
find . -type f -exec grep -nH -ie FORM_DIRECTIVES {} +
./lib/components/datepicker/date_picker.dart:16:      FORM_DIRECTIVES
./lib/components/datepicker/date_picker_popup.dart:15:      FORM_DIRECTIVES
./lib/components/input/input.dart:10:    directives: const [BsMinLengthValidator, BsMaxLengthValidator, CORE_DIRECTIVES, FORM_DIRECTIVES],
./lib/components/timepicker/timepicker.dart:19:    directives: const [CORE_DIRECTIVES, FORM_DIRECTIVES])
./lib/components/typeahead/typeahead.dart:23:      FORM_DIRECTIVES
```

**Comment by chalin** [comment]
Ping. How is this coming along?

**Comment by luisvt** [comment]
The version `0.7.1` should support `angular 4.0.0-alpha+2`, please test it.

**Comment by chalin** [comment]
It works with alpha+2, thanks!
But we're at 4.0.0-alpha+3 now :).

**Comment by luisvt** [comment]
`ng_bootstrap 0.8.0` now supports `angular 4.0.0-alpha+3`

**Comment by chalin** [comment]
Yes, it works nicely, thanks.
